### ISSUE TITLE
yung font ng side nav bar, sobrang liit sa ibang monitor

### ISSUE THREAD

**Issue by CodeMessPro** [CodeMessPro/IPCR#15]

**Comment by OpSlimepc** [comment]
try mo yung vw na font size responsive sya

**Comment by SeffanaAlliera** [comment]
![image](https://github.com/CodeMessPro/IPCR/assets/51997833/9ee5d029-a443-4b56-9ec0-6b1be5b07313)
etong part na to sadya ba 6% di ba masyado maliit?

**Comment by SeffanaAlliera** [comment]
done changing sizes set to 100% works fine on me dont know about other monitors ;) reopen na lang issue if may mali
